title: "VC Web Wallet"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
ga_tracking: G-R8D9K4GZVQ
ga_tracking_anonymize_ip: true
aux_links:
  "RCL SSL Docs on GitHub":
    - "https://github.com/rcl-vc/docs-vc-web-wallet"
callouts:
  information:
    title: Information
    color: blue
  warning:
    title: Warning
    color: red